version: "3.5"
name: cover-generator
services:
  server:
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - .env
  db:
    restart: always
    image: postgres:16.1-bullseye
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"